name: Actions

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: actions-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  diff-check:
    name: Diff check
    uses: ./.github/workflows/diff-check.yml
    with:
      runner: ubuntu-latest
    permissions:
      contents: read
  workflow-lint:
    name: Workflow lint
    uses: ./.github/workflows/workflow-lint.yml
    with:
      runner: ubuntu-latest
    permissions:
      contents: read

  secret-scan:
    name: Secret scan
    uses: ./.github/workflows/secret-scan.yml
    with:
      runner: ubuntu-latest
    permissions:
      contents: read
